import type { DepthChartResponse } from "../../api/players";

/** Representative NYY-style depth chart fixture for design screenshots. */
export const depthChartsDesignFixture: DepthChartResponse = {
  teamId: 147,
  generatedAt: "2026-05-16T21:54:00.000Z",
  season: 2026,
  rosterCount: 26,
  rosterLimit: 26,
  positions: {
    SP: [
      {
        rank: 1,
        playerId: 694973,
        playerName: "Cam Schlittler",
        primaryPosition: "P",
        status: "Active",
        usageStarts: 1,
        usageAppearances: 7,
        outOfPosition: false,
        needsManualReview: false,
        reasons: [],
      },
      {
        rank: 2,
        playerId: 701542,
        playerName: "Will Warren",
        primaryPosition: "P",
        status: "Active",
        usageStarts: 1,
        usageAppearances: 7,
        outOfPosition: false,
        needsManualReview: false,
        reasons: [],
      },
      {
        rank: 3,
        playerId: 671922,
        playerName: "Ryan Weathers",
        primaryPosition: "P",
        status: "Active",
        usageStarts: 1,
        usageAppearances: 7,
        outOfPosition: false,
        needsManualReview: false,
        reasons: [],
      },
    ],
    RP: [
      {
        rank: 1,
        playerId: 641555,
        playerName: "Clay Holmes",
        primaryPosition: "P",
        status: "Active",
        usageStarts: 0,
        usageAppearances: 7,
        outOfPosition: false,
        needsManualReview: false,
        reasons: [],
      },
    ],
    C: [],
    "1B": [],
    "2B": [],
    "3B": [],
    SS: [],
    LF: [],
    CF: [],
    RF: [
      {
        rank: 1,
        playerId: 592450,
        playerName: "Aaron Judge",
        primaryPosition: "RF",
        status: "Active",
        usageStarts: 0,
        usageAppearances: 7,
        outOfPosition: false,
        needsManualReview: false,
        reasons: [],
      },
      {
        rank: 2,
        playerId: 682987,
        playerName: "Spencer Jones",
        primaryPosition: "RF",
        status: "Active",
        usageStarts: 0,
        usageAppearances: 7,
        outOfPosition: false,
        needsManualReview: false,
        reasons: [],
      },
      {
        rank: 3,
        playerId: 641355,
        playerName: "Cody Bellinger",
        primaryPosition: "LF",
        status: "Active",
        usageStarts: 0,
        usageAppearances: 7,
        outOfPosition: false,
        needsManualReview: false,
        reasons: [],
      },
    ],
    DH: [],
  },
  manualReview: [],
  constraints: {
    rosterLimitRespected: true,
    note: "Active roster within limit",
  },
};
